### ISSUE TITLE
Issue: Channel Operator change should refresh the list os users in the channel

### ISSUE THREAD

**Issue by MGranatels** [MGranatels/IRC#43]
When the operators of the channel are changed their name display should have a green icon to show they are channel op

This is already implemented however we have some bugs, when I remove the op status it does not refresh the channel name, even tough I'm calling the broadcast message function. 

For some reason the program only adds the green icon to the first and second user that are added has chann opp after that it does not change the icon even if we remove or add more chann op.

**Comment by gabriela-freitas** [comment]
I believe it's fixed. It was missing the ENDOFNAMES message when brodcasting the name's list

**Comment by gabriela-freitas** [comment]
I added this function to improve the code readability  and avoid this confusion later
