### ISSUE TITLE
Implementation of WHO

### ISSUE THREAD

**Issue by MGranatels** [MGranatels/IRC#53]
WHO
Syntax:

WHO [<name> ["o"]]
Returns a list of users who match <name> If the flag "o" is given, the server will only return information about IRC operators. Defined in RFC 1459.

**Comment by gabriela-freitas** [comment]
I believe it's done. 
You have three options

`/WHO` -> returns a list of all users in server
`/WHO <channel name>` -> returns a list with all users in channel
`/WHO <channel_name> o ` -> returns a list with all users that are channops for that channel
